analytics: {}
color:
  brandColors:
    - '#000000'
    - '#854700'
    - '#000000'
    - '#F08000'
    - '#F8C890'
  brandStrength: 1
  lightness: 0.275553
  rhythmicContrast: 0.736906
  saturation: 0.502397
cta: {}
layout_spectrum: 0
name: TPart
opengraph: {}
purpose: []
typography_spectrum: 0.716216
